services:
  postgres:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432",
        ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app-net

  payment-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    ports:
      - "${PAYMENT_SERVICE_PORT}:3001"
    env_file:
      - ./payments-service/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:3000"
    env_file:
      - ./api-gateway/.env.docker
    depends_on:
      payment-service:
        condition: service_started
      notification-service:
        condition: service_started
    networks:
      - app-net

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:3002"
    env_file:
      - ./notification-service/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
    driver: bridge
